# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20171003_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedsms',
            name='tophone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
