# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20171003_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendedsms',
            old_name='tophone',
            new_name='to',
        ),
    ]
